### ISSUE TITLE
git.PlainClone() doesn't set tracking for local branches

### ISSUE THREAD

**Issue by boogie-byte** [src-d/go-git#683] opened 2017-12-07 13:54 UTC
Here is my code:
```
co := &git.CloneOptions{URL: urlToRepo}
_, err := git.PlainClone(dir, false, co)
if err != nil {
	fmt.Println(err)
} else {
	fmt.Println("done")
}
```
After cloning a repo using `git.PlainClone()`, I expected that local repo has tracking set for all fetched branches (as `git clone` would normally do). However, it looks like this is not the case: 
```
$ git rev-parse --abbrev-ref --symbolic-full-name @{u}
fatal: no upstream configured for branch 'master'
```
Is this an expected behavior? Am I doing something wrong?

**Comment by orirawlings** [comment] 2017-12-07 14:34
You aren't doing anything wrong @boogie-byte. It just isn't currently implemented.

This is a duplicate of #313 

It is also related to #600 (a.k.a lack of support in config module for upstream branch information)

**Closed** 2017-12-07 14:35 UTC
Labels: duplicate
