### ISSUE TITLE
Can't push to private repo using SSH key

### ISSUE THREAD

**Issue by mdelillo** [src-d/go-git#310] opened 2017-03-16 22:24 UTC
Hi, I'm having some trouble pushing a commit to a private repo. I see the commit on my remote but my code hangs on the `remote.Push()` call.

Here's some sample code to reproduce the issue I'm running into:

```golang
package main

import (
	"fmt"
	"golang.org/x/crypto/ssh"
	"io/ioutil"
	"os"
	"os/exec"
	"path/filepath"
	"gopkg.in/src-d/go-git.v4"
	gitssh "gopkg.in/src-d/go-git.v4/plumbing/transport/ssh"
	"strconv"
	"time"
)

func main() {
	repoUrl := os.Getenv("REPO_URL")
	deployKey := os.Getenv("DEPLOY_KEY")

	gitDir, err := ioutil.TempDir("", "go-git-test")
	checkError(err)
	defer os.RemoveAll(gitDir)

	signer, err := ssh.ParsePrivateKey([]byte(deployKey))
	checkError(err)
	auth := &gitssh.PublicKeys{User: "git", Signer: signer}
	repo, err := git.PlainClone(gitDir, false, &git.CloneOptions{URL: repoUrl, Auth: auth})
	checkError(err)

	commitChange(gitDir)

	err = repo.Push(&git.PushOptions{Auth: auth})
	checkError(err)

	fmt.Println("Never gets here")
}

func commitChange(gitDir string) {
	timestamp := strconv.FormatInt(time.Now().UnixNano(), 10)
	ioutil.WriteFile(filepath.Join(gitDir, timestamp), nil, 0644)
	err := run(gitDir, "add", "-A")
	checkError(err)
	err = run(gitDir, "-c", "user.name=TEST", "-c", "user.email=<>", "commit", "-m", "Commit at "+timestamp)
	checkError(err)
}

func checkError(err error) {
	if err != nil {
		panic(err)
	}
}

func run(dir string, args ...string) error {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	return cmd.Run()
}
```

I've tracked it down to these calls:
[`pushHashes`](https://github.com/src-d/go-git/blob/5f4169fe242e7c80d779984a86a1de5a1eb78218/remote.go#L114) -> [`sess.ReceivePack`](https://github.com/src-d/go-git/blob/5f4169fe242e7c80d779984a86a1de5a1eb78218/remote.go#L529) -> [`s.Command.Wait`](https://github.com/src-d/go-git/blob/5f4169fe242e7c80d779984a86a1de5a1eb78218/plumbing/transport/internal/common/common.go#L281) -> [`s.exitStatus`](https://github.com/golang/crypto/blob/728b753d0135da6801d45a38e6f43ff55779c5c2/ssh/session.go#L383)

But I'm not really sure where to go from there. Am I missing something?

Thanks!

**Comment by kimh** [comment] 2017-03-19 14:10
Could it be the case that your `deployKey` doesn't have write access? (deploy key is read-only by default if you are using Github)

**Comment by mdelillo** [comment] 2017-03-19 14:14
I've verified that the deploy key has write access. My example code
successfully pushes a commit but hangs at the end.

**Comment by smola** [comment] 2017-04-06 13:11
@mdelillo Thank you for taking the time to report this issue. We're looking into it.

**Comment by ajnavarro** [comment] 2017-05-23 10:29
@mdelillo I cannot reproduce the problem using a private BitBucket repository, could you test it using the master version of go-git? Thanks.

**Comment by mdelillo** [comment] 2017-05-30 00:43
@ajnavarro I've updated to the latest version but am still seeing the same issue (I've updated my example with the new import paths). I haven't tested against a private bitbucket repository though, only github.

I'm using go 1.8.3 on mac, but I've also reproduced using the [golang docker container](https://hub.docker.com/_/golang/).

**Comment by smola** [comment] 2017-06-12 14:09
@mdelillo Sorry for the delay on this!
I got a fix for this issue here: https://github.com/src-d/go-git/pull/418
It should be merged soon.

**Comment by smola** [comment] 2017-06-13 14:31
Confirmed. This is now fixed in master.

**Closed by smola** 2017-06-13 14:31 UTC
Labels: bug

**Comment by mdelillo** [comment] 2017-06-13 17:07
@smola This fixed my issue, thank you!
