### ISSUE TITLE
Shows deleted tags

### ISSUE THREAD

**Issue by sh0rez** [src-d/go-git#983] opened 2018-10-12 13:02 UTC
Apparently, go-git is able to discover tags that have been deleted.

Steps to reproduce:

Considering this snippet:
```go
package main

import (
	"fmt"

	git "gopkg.in/src-d/go-git.v4"
	"gopkg.in/src-d/go-git.v4/plumbing/object"
)

func main() {
	repo, err := git.PlainOpen(".")
	if err != nil {
		panic(err)
	}
	tags, err := repo.TagObjects()
	if err != nil {
		panic(err)
	}

	tags.ForEach(func(t *object.Tag) error {
		fmt.Println(t)
		return nil
	})
}
```

Do the following steps:
1. Create a new git repo
`$ git init`
2. Run the snippet. As expected, there is no output.
3. Create a tag:
```
$ touch test
$ git add test
$ git commit -m "test"
$ git tag -am "test" 1.0.0
```
4. Run again, the tag is shown:
```
$ go run main.go
tag 1.0.0
Tagger: shorez <me@shorez.de>
Date:   Fri Oct 12 14:51:13 2018 +0200

test

commit 284da2eb4c87c0467c87ce131156d75c74d84736
Author: shorez <me@shorez.de>
Date:   Fri Oct 12 14:50:52 2018 +0200

    test
```
6. Delete the tag:
`git tag -d 1.0.0`
7. Run the snippet again:
```
 go run main.go
tag 1.0.0
Tagger: shorez <me@shorez.de>
Date:   Fri Oct 12 14:51:13 2018 +0200

test

commit 284da2eb4c87c0467c87ce131156d75c74d84736
Author: shorez <me@shorez.de>
Date:   Fri Oct 12 14:50:52 2018 +0200

    test
```
**Unlike expectations, the tag is still shown, but the git cli does not seem to know about it:**
```shell
$ git tag
# nothing here
```
And there is no ref in the folder:
```
$ find .git/refs                                                                                                                                                                                        
.git/refs
.git/refs/heads
.git/refs/heads/master
.git/refs/tags
```

I really have no idea why this is even possible, so maybe somebody can help?

Thanks,
sh0rez

**Comment by aubm** [comment] 2018-10-13 11:41
For the record, deleting the tag using `repo.DeleteObject` make it disappear for good.

**Comment by agimenez** [comment] 2018-10-24 12:48
The problem is that repo.TagObjects calls repo.Storer.IterEncodedObjects. Storer is an interface, and the Filesystem implementation (the one that reads from the .git directory), just loops over all the objects inside `.git/objects`, and only filters out the ones that are of type Tag.

Git by design always performs non-destructive operations, so when you delete a tag, you are only deleting the reference (`.git/refs/tags`) to the commit, not the particular "tag" object, that will stay forever in the repository (unless you run `git fsck`, I guess).

I'm not acquainted with the codebase, so I'm not sure how to fix this, but I'd be happy to help if someone points me in the right direction.

**Comment by sh0rez** [comment] 2018-10-25 18:52
> I'm not acquainted with the codebase, so I'm not sure how to fix this, but I'd be happy to help if someone points me in the right direction.

I'm not in the code either, but I believe go-git should behave like the real git and use the `refs` instead discovering them from the objects. So probably just change the implementation of `repo.TagObjects` to return the `objects` the `refs` of type `tag` point to? From my point of view this should be the desired behaviour ...

**Comment by agimenez** [comment] 2018-10-26 10:08
Yeah. I mean, I know **what** to do (exactly what you proposed), but not **how** for this codebase from the design point of view :)

The problem I see is that various functionalities related with "fetching objects" are generalized, and the code passes around the type of object to filter by, and now that I think about it, this should be the way to go IMHO. For all type of objects only fetch from whatever tip is in `refs/` instead accessing the objects directory directly as it can contain spureous/dangling objects.

I'll try to give it a shot the following days.

**Comment by orirawlings** [comment] 2018-10-26 14:08
`TagObjects` will only return annotated tags. And any which appear in the object store (whether they are referenced or not).

If you are trying to replicate `git tag` you should iterate over tag references instead (this is necessary to support both lightweight and annotated tags). Iterating over references would also allow you to skip tags that have been deleted (aka unreferenced).

See https://godoc.org/gopkg.in/src-d/go-git.v4#Repository.References , filter out references that don't start with `refs/tags/`

**Comment by smola** [comment] 2018-10-26 14:15
@orirawlings just got the response faster :wink:, so what he said, and some more details:

@sh0rez You will achieve your desired behavior by using the [Tags](https://godoc.org/gopkg.in/src-d/go-git.v4#Repository.Tags) function, instead of [TagObjects](https://godoc.org/gopkg.in/src-d/go-git.v4#Repository.TagObjects).

* `Tags` returns tag _references_. The behaviour is analogous to `git tag`.
* `TagObjects` returns all tag _objects_, no matter if they are reachable from a reference or not. Which is analogous to something like `git cat-file --batch-check --batch-all-objects | grep ' tag '`.

Most of our iterators (`TagObjects`, `Commits`, etc) return all objects whether they are reachable or not. This is more performant (computing reachability is expensive), but sometimes unexpected depending on the use case. Reachability can be checked with the `revlist` package, the `Walk*` functions, etc.

This behavior cannot really change in v4, since it would be not backwards compatible.

**Comment by smola** [comment] 2018-10-26 14:16
Closing as `invalid`, since current behavior works as designed in go-git v4.

**Closed by smola** 2018-10-26 14:16 UTC
