### ISSUE TITLE
Push using memory.Storage results in a dirty index

### ISSUE THREAD

**Issue by glibsm** [src-d/go-git#922] opened 2018-08-17 23:18 UTC
Really confused, any help is greatly appreciated.

I've been stuck trying to figure out this problem for a while. I thought that it was something in my usage of go-git, but I seem to have narrowed down the problem to the in-memory store.

## Repro case

- Plain clone into local bare repository
- Clone from that plain repository into in-memory git.Repository
- Add a commit into said git repository
- Push the changes
- Clone remote again (in this ticket, using a command line git)
- Newly cloned repository has dirty status (?? I didn't even think it was possible)

The last step can be replaced by some other validation method (plumbing or other). I've found that for me it was easiest to turn to command line git porcelain.

There is an intermediate step to create a local bare repository in order to push into it. This also happens when a real remote repo is cloned and pushed into.

## Repro code

You may note a commented out `filesystem.Storage`. Running this same code with filesystem storage instead of in-memory does not encounter this issue, which led me to believe the memory store might be a suspect.

```go
package main

import (
    "fmt"
    "io"
    "log"
    "os"
    "os/exec"
    "time"

    "gopkg.in/src-d/go-billy.v4/memfs"
    "gopkg.in/src-d/go-git.v4"
    "gopkg.in/src-d/go-git.v4/plumbing/object"
    "gopkg.in/src-d/go-git.v4/storage/memory"
)

const (
    remotePath = "./remote.git"
    workerPath = "./worker"
)

func main() {
    // delete the remote as it's going to be re-created in this main...
    os.RemoveAll(remotePath)
    os.RemoveAll(workerPath)

    // plain clone go-git testing repo as bare (used as push remote)
    _, err := git.PlainClone(remotePath, true /*bare*/, &git.CloneOptions{
        URL: "https://github.com/git-fixtures/tags.git",
    })

    // clone the "remote" into an in-memory working repository
    fs := memfs.New()

    // Replacing the memory storage with filesystem backed storage seems to work
    // correctly. However, with memory storage the index seems to be out of sync
    // with the worktree...
    storage := memory.NewStorage()
    // storage, _ := filesystem.NewStorage(osfs.New("./intermediate.git"))

    r, err := git.Clone(storage, fs, &git.CloneOptions{URL: remotePath})
    if err != nil {
        log.Fatal("failed to create a worker repo ", err)
    }

    // write out files with their names as data, and add each to index
    wt, err := r.Worktree()
    if err != nil {
        log.Fatal("failed to get worktree")
    }
    for _, fname := range []string{"a", "b", "c"} {
        // create
        f, err := fs.Create(fname)
        if err != nil {
            log.Fatal("failed to create file", err)
        }

        // write + close
        _, err = io.WriteString(f, fmt.Sprintf("Hello world from %s\n", fname))
        if err != nil {
            log.Fatal("failed to write stuff into file", err)
        }
        err = f.Close()
        if err != nil {
            log.Fatal("failed to close file ", err)
        }

        // add file to the index
        if _, err := wt.Add(fname); err != nil {
            log.Fatal("error adding", err)
        }
    }

    // commit the added files
    _, err = wt.Commit(
        "this is a commit",
        &git.CommitOptions{
            Author: &object.Signature{
                Name: "John Doe", Email: "john@doe.org", When: time.Now(),
            },
        })
    if err != nil {
        log.Fatal("error committing", err)
    }

    // push the changes to remote (using default options)
    if err := r.Push(&git.PushOptions{}); err != nil {
        log.Fatal("error pushing", err)
    }

    // use system git for validation
    // a clean state is expected here...
    err = exec.Command("git", "clone", remotePath, workerPath).Run()
    if err != nil {
        log.Fatal("failed to git clone ", err)
    }

    status := exec.Command("git", "-C", workerPath, "status")
    out, err := status.CombinedOutput()
    if err != nil {
        log.Fatal("failed to get status ", err)
    }

    fmt.Println(">>> git status: ", string(out))
}
```

Running it results in the following output:
```
>>> git status:  On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   a
        modified:   b
        modified:   c
```

Doing some more validation on the command line:
```
$ cd worker
$ git status
# On branch: master  |  [*] => $e*
#
➤ Changes to be committed
#
#       modified:  [1] a
#       modified:  [2] b
#       modified:  [3] c
#
$ git show
commit da9635a899ff8955a845ddc3905a4c1d26ad985c (HEAD -> master, origin/master, origin/HEAD)
Author: John Doe <john@doe.org>
Date:   Fri Aug 17 15:48:50 2018 -0700

    this is a commit

diff --git a/a b/a
new file mode 100644
index 0000000..b0b8a63
--- /dev/null
+++ b/a
@@ -0,0 +1 @@
+Hello world from a
diff --git a/b b/b
new file mode 100644
index 0000000..b49df1d
--- /dev/null
+++ b/b
@@ -0,0 +1 @@
+Hello world from b
diff --git a/c b/c
new file mode 100644
index 0000000..f8c44c2
--- /dev/null
+++ b/c
@@ -0,0 +1 @@
+Hello world from c
```

The `git show` output appears correct. It creates some new files which have correct content. The files are also correctly on disk.

```
$ cat *
Hello world from a
Hello world from b
Hello world from c
```

## Versions

As of the time of writing this ticket, i'm using the latest releases of billy and go-git.

```
[[projects]]
  name = "gopkg.in/src-d/go-billy.v4"
  revision = "83cf655d40b15b427014d7875d10850f96edba14"
  version = "v4.2.0"

[[projects]]
  name = "gopkg.in/src-d/go-git.v4"
  revision = "7b6c1266556f59ac436fada3fa6106d4a84f9b56"
  version = "v4.6.0"
```

**Comment by glibsm** [comment] 2018-08-28 21:44
Appears to be the same as https://github.com/src-d/go-git/issues/881 

Running git-fsck on using the directory that this main.go produces results in the same error:
```
error in tree d9bc13bf39c3fcaa4baa05b5c83d72df60f89d2a: treeNotSorted: not properly sorted
Checking object directories: 100% (256/256), done.
Checking objects: 100% (7/7), done.
```

**Comment by smola** [comment] 2018-09-06 15:48
Closing as duplicate of https://github.com/src-d/go-git/issues/881 (which already has a PR fixing it).

**Closed by smola** 2018-09-06 15:48 UTC
