### ISSUE TITLE
It's unclear how to use the NewSSHAgentAuth() helper

### ISSUE THREAD

**Issue by gtaylor** [src-d/go-git#397] opened 2017-05-19 22:23 UTC
Here's what I'm attempting with git master and go 1.8.1:
```
import (
	"fmt"
	"os"
	"gopkg.in/src-d/go-git.v4"
	"gopkg.in/src-d/go-git.v4/plumbing/transport/ssh"
)

...

        sshAuth, err := ssh.NewSSHAgentAuth("git")
	if err != nil {
		return err
	}
	pullOpts := git.PullOptions{
		Progress: os.Stdout,
		Auth:     sshAuth,
	}
	if err := repo.Pull(&pullOpts); err != nil {
		if err == git.NoErrAlreadyUpToDate {
			fmt.Printf("GIT: %s is already up-to-date.\n", localPath)
		} else {
			return err
		}
	}
```
I keep getting:
```
ssh: must specify HostKeyCallbackexit status 1
```
I'm almost certainly doing something wrong, but it's not clear how I should be doing this.

**Comment by smola** [comment] 2017-05-22 07:44
@gtaylor Thanks for reporting this.

We definitely need an example for both SSH agent and public keys auth, since this is a recurring question.

**Comment by smola** [comment] 2017-05-22 09:09
I cannot reproduce this issue. @gtaylor: can you update `golang.org/x/crypto/...`?

/cc @mcuadros @alcortesm if you can provide any further feedback on this, feel free to jump in ;-)

**Comment by alcortesm** [comment] 2017-05-22 14:45
I'm sorry, I cannot reproduce the problem.

@gtaylor can you provide a reproducible example?

**Comment by greenboxal** [comment] 2017-05-22 20:18
This is an issue with `v4-rc9`, this issue doesn't exist on `master`.

Still, I can't clone using `master` as the authentication fails.

    An error ocurred during the deployment: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**Comment by smola** [comment] 2017-05-23 12:29
@greenboxal Which auth method are you using?

**Comment by greenboxal** [comment] 2017-05-23 12:33
SSH Agent. I tried either using the default auth or explicitly passing an instance of the SSHAgentAuth.

I'm trying to clone a GitHub private repository. I can proceed normally using git on the command line, the SSH agent is working as well as I'm able to forward it through SSH.

I'm on macOS btw.

**Comment by gtaylor** [comment] 2017-05-23 16:37
> I cannot reproduce this issue. @gtaylor: can you update golang.org/x/crypto/...?

@smola Updated and I'm still seeing the issue.

> This is an issue with v4-rc9, this issue doesn't exist on master.

@greenboxal I'm getting this while running master, ala:
```
go get -u gopkg.in/src-d/go-git.v4/...
```
I'm on Ubuntu 16.04.2 LTS. My agent is definitely running, since I use it for other things.

**Comment by greenboxal** [comment] 2017-05-24 18:31
@gtaylor The command you ran doesn't update go-git to master, only to the latest release (commit in the case) of the v4 branch.

Try getting master manually into your GOPATH or use glide and set the version to master.

**Comment by smola** [comment] 2017-05-25 08:28
@gtaylor We released v4.0.0-rc10, so the v4 branch should be already working, just run `go get -u gopkg.in/src-d/go-git.v4/...` again.

**Comment by greenboxal** [comment] 2017-05-25 12:54
Found out my problem, it seems that my keys weren't on the ssh-agent, so I had to use ssh-add.

Didn't think about that because if I use ssh agent forwarding, I can use my keys inside the remote host. Do someone have any clue about that? Do OpenSSH runs it's own SSH Agent when forwarding?

**Comment by gtaylor** [comment] 2017-05-25 15:34
> We released v4.0.0-rc10

@smola Looks like this fixed the error! I can close this, or we can address the spirit of the issue (by adding an example, probably).

**Comment by kris-nova** [comment] 2017-05-26 16:03
I would agree for adding an example here

I am trying to clone and pull a repo that follows the `git@github.com/org/repo` syntax and it's proving to be fairly difficult. 

All of the example code uses `https://` and I even tried to dig through the tests without much luck..

**Comment by victorgama** [comment] 2017-05-27 15:52
Had the very same problem a couple of hours ago.

@kris-nova After modifying the `clone` example, I managed to clone a private repository using SSH and the `git@github.com:org/repo.git` syntax:

```go
package main

import (
	"fmt"
	"os"
	"os/user"

	"gopkg.in/src-d/go-git.v4/plumbing/transport/ssh"

	"gopkg.in/src-d/go-git.v4"
	. "gopkg.in/src-d/go-git.v4/_examples"
)

// Basic example of how to clone a repository using clone options.
func main() {
	CheckArgs("<url>", "<directory>")
	url := os.Args[1]
	directory := os.Args[2]

	currentUser, err := user.Current()
	CheckIfError(err)

	// Clone the given repository to the given directory
	Info("git clone %s %s --recursive", url, directory)

	// Assuming id_rsa is available at ~/.ssh/id_rsa
	sshAuth, err := ssh.NewPublicKeysFromFile("git", currentUser.HomeDir+"/.ssh/id_rsa", "")
	CheckIfError(err)

	r, err := git.PlainClone(directory, false, &git.CloneOptions{
		URL:               url,
		RecurseSubmodules: git.DefaultSubmoduleRecursionDepth,
		Auth:              sshAuth,
	})

	CheckIfError(err)

	// ... retrieving the branch being pointed by HEAD
	ref, err := r.Head()
	CheckIfError(err)
	// ... retrieving the commit object
	commit, err := r.CommitObject(ref.Hash())
	CheckIfError(err)

	fmt.Println(commit)
}
```

It may be worth mentioning that on my machine, `gopkg.in/src-d/go-git.v4` is a pointing to `v4-rc10` (7e249df).

@smola I can send a PR to include this demo if you want, and, of course, if @gtaylor don't mind. :)

**Comment by smola** [comment] 2017-05-29 10:18
I'm closing this issue.

Check out this for an example running with https and ssh (with agent):
https://github.com/src-d/go-git/pull/399/files#diff-74cab587e6c9068fc80ad6236b72c511

In order to add better runnable (and tested) examples we still need a testing ssh server, which is a pending task.

**Comment by smola** [comment] 2017-05-29 10:19
@victorgama the problem with that example is that it required a specific setup to run with tests and Travis. We're addressing that though by adding a testing ssh server.

**Closed by smola** 2017-05-29 10:18 UTC
Labels: documentation

**Comment by victorgama** [comment] 2017-05-29 14:26
@smola Oh, I see! Glad you solved it. Thank you! 🙌
