### ISSUE TITLE
http transport should not attempt to parse error bodies

### ISSUE THREAD

**Issue by taralx** [src-d/go-git#326] opened 2017-04-05 20:04 UTC
When we get back an HTTP error in response to `?service=upload-pack`, it appears that we attempt to parse the body instead of propagating the error. This results in weird "invalid pkt-len" errors instead of a useful 500 or 400 or whatever.

**Comment by smola** [comment] 2017-04-06 12:47
@taralx Thank you for taking the time to report this.

I'm closing this issue as duplicate of https://github.com/src-d/go-git/issues/322#issuecomment-292154719 since this is one of the few cases that we do not handle correctly.

**Closed by smola** 2017-04-06 12:47 UTC
