### ISSUE TITLE
Basic git functionalities needed

### ISSUE THREAD

**Issue by magederek** [src-d/go-git#197] opened 2016-12-30 03:07 UTC
Is it possible to implement "git checkout" and "git commit" in the next stage? I'm developing a automating deploying tool using go-git. However, I find that some of the essential git methods are not implemented yet so that I have to use command line instead. And the second thing is that the Clone method does not function as "git clone", and I have to use "git checkout master" to retrieve the files. Would you enhance these aspect of go-git? Thanks.

**Comment by mcuadros** [comment] 2016-12-30 04:52
git checkout is coming in a [near future](https://github.com/mcuadros/go-git/commit/72b9e1f06822440efe784e389b7b2de423e03461), I guest that we will be ready at the end of January. 

About `git commit` is also planned but I don't have any date for it sorry.

**Comment by smola** [comment] 2017-04-06 13:09
Basic checkout is already implemented. Closing this issue as duplicate of https://github.com/src-d/go-git/issues/256

**Closed by smola** 2017-04-06 13:09 UTC
Labels: enhancement
